### ISSUE TITLE
System Config Save JS Error

### ISSUE THREAD

**Issue by Sdfendor** [MahoCommerce/maho#49]
Currently it is not possible to save the config in the adminhtml form. Navigation is no problem, changes to the inputs isn't either. But saving the config by clicking the button does nothing. There are JS issues: 
![image](https://github.com/user-attachments/assets/9c8ee5f8-b642-4944-8eb1-2c04e14f5a08)
The Validation object seems to be missing.
![image](https://github.com/user-attachments/assets/88d907d1-254c-4bd6-ab86-c6f1f8e8ce60)
 
I could reproduce this in Edge and Firefox. It feels like a general problem.

**Comment by fballiano** [comment]
@Sdfendor are you having this on a specific config section? cause the validate-per-page thing seems to be used in the "catalog" section but I can save that section with no problem

**Comment by Sdfendor** [comment]
Ok I dug a little deeper and stumbled upon a 404 for the validation.js requesting js/prototype/validation.js but it's now located directly within the js dir. So I deleted my whole cache directory and afterwards the correct file has been requested and everything works fine. Sorry for not trying more to troubleshoot before opening an issue.
