### ISSUE TITLE
swatches are not working 100% correctly

### ISSUE THREAD

**Issue by fballiano** [MahoCommerce/maho#53]
<img width="580" alt="Screenshot 2024-11-07 alle 20 57 17" src="https://github.com/user-attachments/assets/042d4217-eac1-4c7d-b9b7-5cbf22912995">

the image files in the sidebar should be the same used below the product, but they're not

**Comment by empiricompany** [comment]
per me è corretto perchè nel caso di "Plaid Cotton Shirt" gli swatches vengono definiti nella gallery del prodotto e prendono il sopravvento, mentre nella layered navigation vengono usati gli swatches caricati in media/wysiwyg/swatches

per esempio per il colore Khaki
![ Plaid Cotton Shirt ](https://github.com/user-attachments/assets/03dd7e77-d8d6-4c9f-84ab-47ca29119e2d)
in quello specifico prodotto viene sostituito dallo swatches caricato nella gallery con suffisso "-swatch"
mentre nella layered usa wysiwyg/swatches/khaki.png
ha sempre funzionato così

**Comment by fballiano** [comment]
ahhhh allora è un "problema" di come sono stati creati quei prodotti li, ho capito bene?

**Comment by empiricompany** [comment]
non è un "problema" funziona proprio così, un'altra alternativa per caricare su uno specifico prodotto uno swatch diverso è caricarlo nel rispettivo figlio del configurabile se non ricordo male dovrebbe prendere quello.

questo dovrebbe essere l'ordine e rispettivi fallback:
- wysiwyg/swatches/valore-attributo.png
- gallery di prodotto con label Valore Attributo-swatch
- gallery del figlio del prodotto con la specifica configurazione (solitamente anteprima del prodotto)

nella layered invece legge sempre e solo in wysiwyg/swatches/
anche perchè come in uqetso caso per Khaki non saprebbe quale usare, di solito si usa in tutto il catalogo una delle 3 modalità salvo casi particolari

**Comment by fballiano** [comment]
oki capito :-)
