### ISSUE TITLE
Missing button close in all dialogs

### ISSUE THREAD

**Issue by empiricompany** [MahoCommerce/maho#61]
I can close dialog only with ESC from keyboard

![catalog](https://github.com/user-attachments/assets/a080132d-9926-4741-aadf-c03f10947382)
![widget](https://github.com/user-attachments/assets/c9e04fb2-3cbc-4a2a-8f7a-702e5dc54b9a)

**Comment by fballiano** [comment]
should be solved now

**Comment by fballiano** [comment]
it wasn't added from the start because many dialogs have buttons in the lower part of the dialog ;-)
