### ISSUE TITLE
double span was removed

### ISSUE THREAD

**Issue by fballiano** [MahoCommerce/maho#67]
but it seems to be back...

**Comment by fballiano** [comment]
it was done only in the base templates, https://github.com/MahoCommerce/maho/commit/51ced003f8f2752d83397dea3169f9c90f693053 brings it to the RWD and we'll later do that for adminhtml too

**Comment by fballiano** [comment]
and with https://github.com/MahoCommerce/maho/commit/b7b004608ebf9eb226c2b327d3e9e0d5ec89c676 this should be finished

**Comment by justinbeaty** [comment]
Nice, all those duplicate spans are so unnecessary!
