### ISSUE TITLE
RWD same size for all swatches

### ISSUE THREAD

**Issue by fballiano** [MahoCommerce/maho#77]
find a way to solve this

<img width="283" alt="Screenshot 2024-12-20 alle 08 54 50" src="https://github.com/user-attachments/assets/2abfebdc-7e85-4b4a-9f85-d0c684f02d11" />

**Comment by justinbeaty** [comment]
How about CSS Grid? I haven't fully tested the patch, not sure if it affects any other pages other than layered nav.

![image](https://github.com/user-attachments/assets/00b05771-606c-4f0e-ab70-197631f8b435)


```diff
diff --git a/public/skin/frontend/rwd/default/css/styles.css b/public/skin/frontend/rwd/default/css/styles.css
index abf12a2f0f..84f8e4f364 100644
--- a/public/skin/frontend/rwd/default/css/styles.css
+++ b/public/skin/frontend/rwd/default/css/styles.css
@@ -6829,14 +6829,18 @@ body:not(.opc-has-progressed-from-login) .opc.opc-firststep-login .section#opc-l
 }
 
 #narrow-by-list .configurable-swatch-list {
-  display: flex;
-  flex-wrap: wrap;
+  display: grid;
+  grid-template-columns: repeat(3, 1fr);
+  grid-column-gap: 5px;
+  grid-row-gap: 5px;
+}
+#narrow-by-list .configurable-swatch-list li {
+  overflow: hidden;
 }
 #narrow-by-list dd .swatch-link {
   border: none;
   line-height: 25px;
-  margin-right: 2px;
-  text-align: left;
+  padding: unset;
 }
 #narrow-by-list dd .swatch-link.has-image {
   line-height: inherit;
@@ -6850,6 +6854,8 @@ body:not(.opc-has-progressed-from-login) .opc.opc-firststep-login .section#opc-l
   line-height: 1.5em;
   margin: 0 5px 0 0;
   padding: 1px 5px;
+  overflow: hidden;
+  text-overflow: ellipsis;
   white-space: nowrap;
 }
 #narrow-by-list dd .swatch-label img {
```

**Comment by fballiano** [comment]
I was testing with grid and flexbox precisely ehehhe I'll try yours ;-)

**Comment by fballiano** [comment]
@justinbeaty I did it in a slightly different way because in the meanwhile I had removed the gray background (which was an unnecessary span inside the `a` and also, gray on gray fails accessibility)

**Comment by fballiano** [comment]
<img width="342" alt="Screenshot 2024-12-20 alle 17 10 46" src="https://github.com/user-attachments/assets/4d20354f-dcce-4338-b0de-c3723cfecb57" />

**Comment by justinbeaty** [comment]
Nice! One thing I noticed was that on certain mobile screen sizes the swatches might be too wide. Could possibly use a media query to increase to 4 columns, but I actually thought it looked fine so I didn't bother.

**Comment by fballiano** [comment]
I've noticed too but if you check on a real mobile phone it's never that large ;-)
