### ISSUE TITLE
Webp format for cached images

### ISSUE THREAD

**Issue by empiricompany** [MahoCommerce/maho#78]
I'm testing the new feature that allows setting and enforcing a format for cached generated images.

this commit: https://github.com/MahoCommerce/maho/commit/36e9e93290d9bc0a40b4db4f0c7a7eb7e53a58a9

I've noticed that if I set the format to WebP, the generated images are fake WebP—they remain in JPG format. Specifically, they have the .webp extension, but if I save the image, it is recognized as JPG.

I tested the same image on the demo site, and when I save the image there, it is correctly recognized as webp. However, on my end, it is identified as a jpg with larger file sizes.

https://demo.mahocommerce.com/accessories/jewelry.html
![demo](https://github.com/user-attachments/assets/f6ee3f79-ece0-45b1-8d1a-801ab23aaeb5)
![sizewebp](https://github.com/user-attachments/assets/79f3aa94-df23-4baf-bd82-a12ddd67b043)

![demo](https://github.com/user-attachments/assets/04e09799-7bca-4246-bada-400605a999ec)
![testwebp](https://github.com/user-attachments/assets/dcd81479-1e8d-457d-8338-6e0772757c32)

**Comment by fballiano** [comment]
weird, the webp support was already in OM since a while, I'll check it out

**Comment by empiricompany** [comment]
Yes, I can successfully handle WebP images, upload them, and modify them, but only if they are natively in WebP format. It seems that no actual conversion to WebP takes place, and only the file extension is changed.

**Comment by fballiano** [comment]
they get converted in the process of creating the thumbnails, but I will retest it

**Comment by fballiano** [comment]
fixed by #79
